# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Streetbees-ios-developer-challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Streetbees-ios-developer-challenge
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 4.0'

  target 'Streetbees-ios-developer-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Streetbees-ios-developer-challengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
